### ISSUE TITLE
Fix Dashboard Link on Subscription Page [UI]

### ISSUE THREAD

**Issue by siddhantdixit** [siddhantdixit/LinkStack#13]
Currently, a user can't go back from the subscription page. The Dashboard link doesn't work correctly. It needs to be fixed.

https://project-linkedlist.herokuapp.com/dashboard/subscription

![image](https://user-images.githubusercontent.com/22856752/195979180-560f14f9-8c95-4fc2-ac27-354f9135146b.png)

**Comment by CodingWarrior33** [comment]
Hey, could you assign this issue to me ...

**Comment by jsvigneshkanna** [comment]
assign this issue to my name

**Comment by Shubh-Bindal** [comment]
pls assign this issue to me
