### ISSUE TITLE
URL Safe Username

### ISSUE THREAD

**Issue by siddhantdixit** [siddhantdixit/LinkStack#3]
- [ ] Usernames may only contain letters, numbers, underscores ("_") and periods (".")
- [ ] Username should be converted toLowercase at backend before processing.

**Comment by vmittal05** [comment]
Hi @siddhantdixit, I can work on this issue.  you need the username validation checks at the front-end login and sign-up pages, right ?

**Comment by siddhantdixit** [comment]
> Hi @siddhantdixit, I can work on this issue.  you need the username validation checks at the front-end login and sign-up pages, right ?

Sure!
